pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:migrationsfdc/migration-test.git
          - cd migration-test.git
          - git push --mirror git@github.com:sfwithsurbhi/migration-test.git